version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello build"
  test-a:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello test-a"
      - run: sleep 5
  test-b:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello test-b"
      - run: sleep 5
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "goodbye"
      - run: sleep 5

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-a:
          requires:
            - build
      - test-b:
          requires:
            - build
      - deploy:
          requires:
            - test-a
            - test-b
