version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello 1"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello 2"
      - run: sleep 5

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
